"""Самодостаточная HTML-памятка с фактическими результатами проверки."""
import base64
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
out = root / 'outputs/go2-perception'
bench = json.loads((out / 'perception-replay-final/benchmark.json').read_text(encoding='utf-8'))
run = bench['captures'][0]

def image(path, kind):
    return f'data:image/{kind};base64,' + base64.b64encode(path.read_bytes()).decode('ascii')

template = '''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Go2 — первые результаты распознавания</title><style>
:root{--ink:#14283e;--muted:#526879;--green:#007c62;--line:#dae4e9;--bg:#f2f6f8}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:17px/1.65 system-ui,Segoe UI,sans-serif}
header{background:#132b40;color:white;padding:52px 24px 42px}header>div,main,footer{max-width:1120px;margin:auto}
.eyebrow{text-transform:uppercase;letter-spacing:.15em;font-size:12px;font-weight:800;color:#a9ebd7}h1{font-size:clamp(31px,5vw,53px);line-height:1.12;max-width:850px;margin:18px 0}header p{color:#d6e2eb;max-width:850px;font-size:19px}
nav{display:flex;gap:18px;flex-wrap:wrap;margin-top:24px}nav a{color:#c5f6e7;text-decoration:none}main{padding:26px 20px 55px}section{background:white;border:1px solid var(--line);border-radius:18px;padding:28px;margin:22px 0}h2{font-size:26px;line-height:1.3;margin:0 0 17px}h3{font-size:19px;margin:0 0 6px}p{margin:12px 0}.muted,figcaption{color:var(--muted)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.stat{background:#e9f5f1;border-radius:12px;padding:21px}.value{font-size:34px;font-weight:800;color:var(--green);line-height:1.2}.stat small{display:block;font-size:13px;line-height:1.5;margin-top:10px}figure{margin:20px 0 0}img{display:block;width:100%;height:auto;border-radius:10px;border:1px solid var(--line)}figcaption{font-size:14px;margin-top:12px}button{background:white;color:var(--ink);border:1px solid #b5c8d3;padding:10px 17px;border-radius:8px;font:inherit;cursor:pointer}button[aria-pressed=true]{background:var(--ink);color:white}.controls{display:flex;gap:10px;flex-wrap:wrap}.note{border-left:4px solid #d48931;background:#fff7eb;padding:16px 20px;border-radius:5px;margin-top:18px}.good{border-left-color:var(--green);background:#edf8f4}.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.flow>div{padding:18px;background:var(--bg);border-radius:10px}.flow b{display:block;margin-bottom:8px}.flow span{font-size:14px;color:var(--muted)}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--line)}th{background:var(--bg)}.tablewrap{overflow-x:auto}li{margin:9px 0}code{font-size:14px;background:#edf2f6;padding:2px 5px;border-radius:4px}details{margin-top:16px;border-top:1px solid var(--line);padding-top:14px}summary{cursor:pointer;font-weight:700}footer{padding:0 22px 40px;color:var(--muted);font-size:13px}a{color:#006887}
@media(max-width:700px){.stats,.flow{grid-template-columns:1fr}section{padding:20px}header{padding:35px 22px}h2{font-size:23px}}
@media print{body{background:white;font-size:11pt}header{background:white;color:var(--ink);padding:0 20px}header p,.eyebrow{color:var(--muted)}nav,.controls,.print{display:none}section{break-inside:avoid;border-radius:0}details{display:block}main{padding-top:0}.stats{grid-template-columns:repeat(3,1fr)}}
</style></head><body><header><div><div class="eyebrow">Команда WOLF · физический полигон · 16 сентября 2026</div><h1>Рампа уже видна программе.<br>До самостоятельного заезда — следующий этап.</h1><p>Получили данные настоящего Go2, выделили рампу на изображении и проверили обработку на Raspberry Pi. Ниже — результат, его ограничения и ближайшие действия.</p><nav><a href="#vision">Камера</a><a href="#geometry">Карта</a><a href="#pi">Проверка на Pi</a><a href="#next">Что дальше</a></nav></div></header>
<main><div class="stats"><div class="stat"><div class="value">10 / 10</div>кадров с найденной рампой<small>Две записи одного почти неизменного ракурса. Это не точность на произвольной трассе.</small></div><div class="stat"><div class="value">@@VISION@@ мс</div>поиск рампы на Raspberry Pi<small>Среднее по 5 кадрам 640 × 360; без чтения файла и рисования разметки.</small></div><div class="stat"><div class="value">@@VOXEL@@ мс</div>анализ воксельной карты<small>Среднее по 3 картам, включая чтение NPZ. Модули измерялись отдельно.</small></div></div>
<section id="vision"><h2>Что распознаёт камера</h2><p>Алгоритм ищет сочетание поперечных планок, боковых границ и поверхности рампы. Один только серый цвет недостаточен: таким же цветом могут быть маты или другие детали.</p><div class="controls"><button id="show-overlay" aria-pressed="true" onclick="switchImage(true)">Показать разметку</button><button id="show-original" aria-pressed="false" onclick="switchImage(false)">Исходный кадр</button></div><figure><img id="overlay" src="@@OVERLAY@@" alt="Камера робота: жёлтым выделена рампа, зелёным предполагаемый вход и ось"><img id="original" src="@@ORIGINAL@@" alt="Исходный кадр фронтальной камеры Go2" hidden style="display:none"><figcaption>Жёлтая рамка — кандидат на рампу; голубые линии — поперечные планки; зелёная линия — предполагаемый ближний край. Зелёная стрелка показывает ось рампы на изображении. Число 0,98 — оценка согласованности признаков, а не вероятность успеха 98%.</figcaption></figure><div class="note"><b>На изображении найдены пиксели, а не готовая цель движения.</b> Расстояние до входа, угол поворота робота, уклон и надёжность поверхности по этому результату не установлены. Стрелку нельзя непосредственно превращать в команду поворота.</div><details><summary>Какие проверки прошли</summary><p>Пять первых кадров, отражение, изменение яркости, перенос и уменьшение изображения, три отрицательных фрагмента: стена, мат, потолок. Затем пять свежих кадров без перенастройки. Все положительные примеры относятся к одной сцене. Гладкие рампы без планок, сильный крен камеры, закрытый или обрезанный вход пока не проверены.</p></details></section>
<section id="geometry"><h2>Что пока даёт лидар</h2><p>Доступный поток содержит обработанную воксельную карту: пространство разбито на ячейки размером <b>5 см</b>. Это не сырые лучи и не гарантия точности 5 см. Мы используем штатный декодер, возвращающий занятые ячейки в метрах.</p><figure><img src="@@MAP@@" alt="Диагностическая карта высот и два неподтверждённых наклонных участка"><figcaption>Оранжевые области — геометрические кандидаты на наклонные поверхности. Не подтверждено, что какая-либо из них является рампой на фото. На карте видны артефакты; пустые места нельзя автоматически считать безопасными для лап.</figcaption></figure><div class="note"><b>Привязка координат ещё не подтверждена.</b> Между двумя записями изменился сообщаемый курс при почти одинаковом изображении. Временные метки карты и позы также расходятся; причина и точность часов не установлены. Это не доказательство конкретной задержки. До проверки нельзя объединять такие данные в маршрут.</div><p>В свежей короткой записи получено около <b>7,71 сообщения карты/с</b> и <b>14,3 кадра камеры/с</b>. В первом замере с другим декодером было 3,62 сообщения карты/с. Это отдельные диагностические замеры, а не доказанная постоянная производительность.</p></section>
<section id="pi"><h2>Что реально запустили на Raspberry Pi</h2><div class="tablewrap"><table><thead><tr><th>Модуль</th><th>Результат</th><th>Среднее / максимум</th></tr></thead><tbody><tr><td>Камера, 640 × 360</td><td>5 кадров, по одному кандидату</td><td>@@VISION@@ / @@VISIONMAX@@ мс</td></tr><tr><td>Геометрия карты</td><td>3 карты, по два наклонных участка</td><td>@@VOXEL@@ / @@VOXELMAX@@ мс</td></tr><tr><td>Проверка записи</td><td>Ошибок полной серии нет</td><td>Пропуски файлов отклоняются</td></tr></tbody></table></div><p>Это обработка сохранённой записи на самом Pi, без команд движения. Она не измеряет полную задержку «датчик → управление» и не подтверждает устойчивость длительного заезда.</p><p>Фактическое окружение: Python 3.14.4, NumPy 2.5.3, OpenCV 5.0, SciPy 1.18.1. ROS 2 на проверенном узле отсутствует. Добавленные зависимости лежат в отдельном каталоге нашей программы. Штатная служба подключения после сбора данных восстановлена.</p><details><summary>Из чего состоит программа</summary><p><code>ramp_vision.py</code> — поиск рампы на изображении. <code>voxel_geometry.py</code> — проверка формата карты и поиск наклонных поверхностей. <code>replay_perception.py</code> — обработка записи и измерение времени. Модули распознавания не соединяются с роботом и не отправляют скорости.</p><p>Карта сохраняется вместе с метаданными. Для следующих записей добавлена явная связь имени NPZ с сообщением. Полные архивные записи обрабатываются только с явным разрешением старого порядка; пропущенный первый кадр больше не сдвигает привязку остальных.</p></details></section>
<section id="next"><h2>Ближайший план</h2><div class="flow"><div><b>1. Проверить координаты</b><span>Уточнить часы, сбросы odom и доступность сырых точек; получить калибровку камеры и положение датчиков.</span></div><div><b>2. Связать изображение с глубиной</b><span>Подтвердить, какие точки относятся к видимой рампе, её краям и пространству перед входом.</span></div><div><b>3. Проверить новые ракурсы</b><span>Боковые подходы, ближний вход, маты и похожие предметы. Сохранять и разбирать ошибки.</span></div><div><b>4. Испытать подход</b><span>После проверки привязки — ограниченный подход по полу при готовности полигона и согласованном способе остановки; затем отдельное испытание подъёма.</span></div></div><div class="note good"><b>Критерий следующего успеха:</b> программа стабильно показывает подтверждённый вход в метрах относительно робота, а не просто выделяет серый четырёхугольник. Прохождение рампы и всей полосы пока не испытано.</div></section><button class="print" onclick="window.print()">Печать / сохранить PDF</button></main>
<footer>Отчёт основан на двух записях датчиков и выполненном тесте на Raspberry Pi от 16.09.2026. Все изображения встроены: этот HTML можно открыть без интернета и передать одним файлом. Паролей и ключей в нём нет.</footer><script>function switchImage(show){document.getElementById('overlay').style.display=show?'block':'none';document.getElementById('original').style.display=show?'none':'block';document.getElementById('original').hidden=show;document.getElementById('show-overlay').setAttribute('aria-pressed',String(show));document.getElementById('show-original').setAttribute('aria-pressed',String(!show));}</script></body></html>'''
values = {
    'VISION': round(run['camera_timing_ms']['mean']), 'VISIONMAX': round(run['camera_timing_ms']['max']),
    'VOXEL': round(run['voxel_timing_ms']['mean']), 'VOXELMAX': round(run['voxel_timing_ms']['max']),
    'OVERLAY': image(out / 'vision-fresh-camera_00.jpg', 'jpeg'),
    'ORIGINAL': image(root / 'outputs/go2-remote-setup/logs/20260916T110043Z/camera_00.jpg', 'jpeg'),
    'MAP': image(out / 'voxel-20260916T110043Z-00.png', 'png'),
}
for key, value in values.items():
    template = template.replace('@@' + key + '@@', str(value))
path = out / 'Go2 — первые результаты распознавания.html'
path.write_text(template, encoding='utf-8')
print(path)
